version: "2"
services:
  rest:
    build: .
    ports:
      - "3000:8080"
    env_file:
      - .env
    logging:
      driver: "splunk"
      options:
        splunk-url: https://10.244.112.158:8088
        splunk-token: ${SPLUNK_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-format: "json"
        splunk-verify-connection: "false"
    restart: on-failure