version: 2
container_config: &container_config
  docker:
    - image: circleci/openjdk:8-jdk-browsers
  working_directory: /home/circleci/qpp-conversion-tool

jobs:
  checkout:
    <<: *container_config
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - qpp-conversion-tool

  build:
    <<: *container_config
    environment:
      MAVEN_OPTS: "-Xms7G -Xmx7G"
    resource_class: large
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: wget -O sonarscanner.zip https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.1.733.zip
      - run: unzip -d . sonarscanner.zip
      - run: cp ./sonar-scanner.properties sonar-scanner-3.0.1.733/conf/sonar-scanner.properties
      - run: mvn --batch-mode clean verify
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: ./tools/bin/sonarqube.sh
      - run:
          name: Creating artifacts
          command: |
            ARTIFACT_DIR=/tmp/artifacts;
            mkdir $ARTIFACT_DIR;
            cp converter/target/converter.jar $ARTIFACT_DIR;
            cp commandline/target/commandline.jar $ARTIFACT_DIR;
            cp rest-api/target/rest-api.jar $ARTIFACT_DIR;
            mkdir -p $ARTIFACT_DIR/coverage/converter;
            cp -R converter/target/site/jacoco $ARTIFACT_DIR/coverage/converter;
            mkdir -p $ARTIFACT_DIR/coverage/rest-api;
            cp -R rest-api/target/site/jacoco $ARTIFACT_DIR/coverage/rest-api;
            mkdir -p ARTIFACT_DIR/coverage/commandline;
            cp -R rest-api/target/site/jacoco $ARTIFACT_DIR/coverage/commandline;

      - store_artifacts:
          path: /tmp/artifacts

  deploy_api:
    docker:
      - image: golang:1.6.4
    working_directory: /home/circleci/qpp-conversion-tool
    steps:
      - attach_workspace:
          at: /home/circleci
      - setup_remote_docker:
          docker_layer_caching: true
      - run: wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py
      - run: python get-pip.py
      - run: pip install ansible
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: ./tools/bin/docker_deploy.sh

  integration_test:
    <<: *container_config
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: mvn clean test -DfailIfNoTests=false -Dtest=*ApiAcceptance*

  ui_test:
    <<: *container_config
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo apt-get install gconf-service libasound2 libatk1.0-0 libcups2 libdbus-1-3 libgconf-2-4 libgtk-3-0 libnspr4 libxcomposite1 lsb-release
      - run: sudo dpkg -i google-chrome.deb
      - run: sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
      - run: rm google-chrome.deb
      - run: cd frontend; rm -f yarn.lock && yarn
      - run: sudo npm install -g protractor;
      - run: cd frontend; yarn run lint;
      - run: cd frontend; yarn run test:ci;
      - run: cd frontend; yarn run e2e:ci;

  ui_deployment:
    <<: *container_config
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: cd frontend; rm -f yarn.lock && yarn
      - run: cd frontend; yarn run build;
      - run: sudo apt-get install python-dev
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: aws s3 sync frontend/dist s3://qpp-conversion-tool-ui --delete

  signal_success:
    <<: *container_config
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: sudo apt-get install jq
      - run: ./tools/bin/signal_success.sh

workflows:
  version: 2
  commit:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - ui_test:
          requires:
            - checkout
      - deploy_api:
          requires:
            #change this to be filtered on the master branch
            - checkout
      - integration_test:
          requires:
            - deploy_api
      - ui_deployment:
          filters:
            branches:
              only: ui_deployment
          requires:
            - ui_test
      - signal_success:
          requires:
            - build
            - ui_test

