version: 2
jobs:
 build:
  java:
    version: openjdk8
  python:
    version: 3.6.1
  services:
    - docker

  - run:
      name: resolve dependencies
      command: cd converter; mvn dependency:resolve
#    - cd converter; mvn dependency:resolve
#    - wget -O sonarscanner.zip https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.1.733.zip
#    - unzip -d . sonarscanner.zip
#    - pip install ansible
#
#test:
#  pre:
#    - cp ./sonar-scanner.properties sonar-scanner-3.0.1.733/conf/sonar-scanner.properties
#  override:
#    - mvn clean verify
#    - ./tools/bin/sonarqube.sh
#  post:
#    - ./tools/bin/docker_deploy.sh
#    - cp converter/target/converter.jar $CIRCLE_ARTIFACTS
#    - cp commandline/target/commandline.jar $CIRCLE_ARTIFACTS
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/converter && cp -R converter/target/site/jacoco $CIRCLE_ARTIFACTS/coverage/converter
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/rest-api && cp -R rest-api/target/site/jacoco $CIRCLE_ARTIFACTS/coverage/rest-api
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/commandline && cp -R rest-api/target/site/jacoco $CIRCLE_ARTIFACTS/coverage/commandline

#dependencies:
#  override:
#    - cd converter; mvn dependency:resolve
#    - wget -O sonarscanner.zip https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.1.733.zip
#    - unzip -d . sonarscanner.zip
#    - pip install ansible
#
#test:
#  pre:
#    - cp ./sonar-scanner.properties sonar-scanner-3.0.1.733/conf/sonar-scanner.properties
#  override:
#    - mvn clean verify
#    - ./tools/bin/sonarqube.sh
#  post:
#    - ./tools/bin/docker_deploy.sh
#    - cp converter/target/converter.jar $CIRCLE_ARTIFACTS
#    - cp commandline/target/commandline.jar $CIRCLE_ARTIFACTS
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/converter && cp -R converter/target/site/jacoco $CIRCLE_ARTIFACTS/coverage/converter
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/rest-api && cp -R rest-api/target/site/jacoco $CIRCLE_ARTIFACTS/coverage/rest-api
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/commandline && cp -R rest-api/target/site/jacoco $CIRCLE_ARTIFACTS/coverage/commandline
